name: Deploy Keycloak to Azure (HTTPS Enabled)

on:
  push:
    branches:
      - main
    paths:
      - keycloak/docker-compose.yaml  # Trigger on updates to this file
      - .github/workflows/keycloak-workflow.yml # Trigger on updates to this workflow
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Deploy Bitnami Keycloak to Azure App Service
      - name: Deploy Keycloak with HTTPS
        run: |
          # Define variables
          RESOURCE_GROUP="noideatt"                     # Replace with your Resource Group name
          APP_NAME="keycloak-bitnami-app"               # Replace with your Azure App Service name
          LOCATION="southeastasia"                      # Replace with the desired Azure region

          # Create an App Service Plan (Linux Free Tier)
          az appservice plan create \
            --name $APP_NAME-plan \
            --resource-group $RESOURCE_GROUP \
            --sku F1 \
            --is-linux \
            --location $LOCATION

          # Deploy the Bitnami Keycloak container to Azure App Service
          az webapp create \
            --resource-group $RESOURCE_GROUP \
            --plan $APP_NAME-plan \
            --name $APP_NAME \
            --deployment-container-image-name bitnami/keycloak:latest

          # Set environment variables for HTTPS configuration
          az webapp config appsettings set \
            --resource-group $RESOURCE_GROUP \
            --name $APP_NAME \
            --settings \
              KEYCLOAK_ADMIN_USER=${{ secrets.KEYCLOAK_ADMIN }} \
              KEYCLOAK_ADMIN_PASSWORD=${{ secrets.KEYCLOAK_ADMIN_PASSWORD }} \
              KEYCLOAK_HTTP_PORT=8080 \
              KEYCLOAK_HTTPS_PORT=8443 \
              KEYCLOAK_ENABLE_HTTPS=true \
              KEYCLOAK_PROXY=edge

      # Step 4: Validate the deployment
      - name: Verify Deployment
        run: |
          # Check deployment URL
          RESOURCE_GROUP="noideatt"
          APP_NAME="keycloak-bitnami-app"

          echo "Keycloak App URL:"
          az webapp show --resource-group $RESOURCE_GROUP --name $APP_NAME --query "defaultHostName" -o tsv

          echo "Access Keycloak via HTTPS:"
          echo "https://<your-app-name>.azurewebsites.net:8443"
