name: Deploy Bitnami Keycloak to Azure Container Apps (ACA)

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/keycloak-workflow.yml
  workflow_dispatch:

jobs:
  deploy-keycloak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure context
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bitnami Keycloak to Azure Container Apps
        run: |
          az containerapp create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name keycloak-noideatt-app \
            --image bitnami/keycloak:latest \
            --environment ${{ secrets.AZURE_CONTAINERAPPS_ENVIRONMENT }} \
            --cpu 0.25 \
            --memory 0.5Gi \
            --ingress external \
            --target-port 8080 \
            --min-replicas 0 \
            --max-replicas 1 \
            --env-vars KEYCLOAK_USER=admin KEYCLOAK_PASSWORD=${{ secrets.KEYCLOAK_PASSWORD }} \
            KEYCLOAK_DB=H2 \
            KEYCLOAK_DB_URL=jdbc:h2:mem:keycloak;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

      - name: Verify deployment
        run: |
          az containerapp show \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name keycloak-noideatt-app \
            --query "{State:properties.provisioningState,URL:properties.configuration.ingress.fqdn}"
