name: Deploy Reading Service Server to Azure (Java 22)

on:
  push:
    branches:
      - main
    paths:
      - reading-service/Dockerfile
      - reading-service/pom.xml
      - reading-service/src/**
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: 'x64'

      - name: Build with Maven
        run: mvn -B package --file reading-service/pom.xml

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/reading-service:latest -f reading-service/Dockerfile reading-service/
          docker push ${{ secrets.DOCKER_USERNAME }}/reading-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Step 1: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 2: Deploy to Azure Container App
      - name: Deploy to Azure Container App
        run: |
          RESOURCE_GROUP=${{secrets.AZURE_RESOURCE_GROUP}}
          CONTAINER_APP_NAME="reading-service-noideatt-app"
          LOCATION="southeastasia"
          
          # Deploy the Docker image to Azure Container App
          az containerapp create \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image ${{ secrets.DOCKER_USERNAME }}/reading-service:latest \
            --cpu 0.25 --memory 0.5Gi \
            --min-replicas 0 \
            --max-replicas 1 \
            --ingress external \
            --target-port 8082 \
            --environment ${{secrets.AZURE_CONTAINERAPPS_ENVIRONMENT}} \
            --env-vars \
              SPRING_DATA_MONGODB_URI=${{ secrets.SPRING_DATA_MONGODB_URI }} \
              SPRING_DATA_MONGODB_DATABASE=${{ secrets.SPRING_DATA_MONGODB_READING_DATABASE }} \
              RESOURCESERVER_JWT_JWK_SET_URI=${{ secrets.RESOURCESERVER_JWT_JWK_SET_URI }} \
              EUREKA_SERVER_URL=${{ secrets.EUREKA_SERVER_URL }} \
              SPRING_PROFILES_ACTIVE=prod
